version: "3.8"

services:
  api-gateway:
    build: ./1-api-gateway
    env_file:
      - ./1-api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - identity
      - post
      - media
      - search
      - redis
      - rabbitmq

  identity:
    build: ./2-identity-service
    env_file:
      - ./2-identity-service/.env
    depends_on:
      - mongo
      - redis
      - rabbitmq

  post:
    build: ./3-post-service
    env_file:
      - ./3-post-service/.env
    depends_on:
      - mongo
      - redis
      - rabbitmq

  media:
    build: ./4-media-service
    env_file:
      - ./4-media-service/.env
    depends_on:
      - mongo
      - rabbitmq
      - redis

  search:
    build: ./5-search-service
    env_file:
      - ./5-search-service/.env
    depends_on:
      - mongo
      - redis
      - rabbitmq

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data:
